FROM ubuntu:latest

ARG CI=default
ARG UNENCRYPTED=default
ARG ENCRYPTED=default
ARG FROMFILE=default

ENV CI=$CI
ENV UNENCRYPTED=$UNENCRYPTED
ENV ENCRYPTED=$ENCRYPTED
ENV FROMFILE=$FROMFILE

RUN mkdir /app
COPY . /app
